version: '3.4'
x-sentry-defaults: &sentry_defaults
  build: 
    context: .
  depends_on:
    - redis
    - postgres-test
  environment:
    SENTRY_SECRET_KEY: some-secret-key
    SENTRY_REDIS_HOST: redis
    SENTRY_DB_NAME: sent
    SENTRY_DB_USER: sent
    SENTRY_POSTGRES_HOST: postgres-test
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: sent
    POSTGRES_DB: sent
  volumes:
    - sentry-data:/data
    # - ./sentry:/etc/sentry
services:
  sentry-web:
    << : *sentry_defaults
    container_name: sentry-web
    ports:
      - "8080:9000"

  sentry-worker:
    << : *sentry_defaults
    command: run worker

  sentry-cron:
    << : *sentry_defaults
    command: run cron

  redis:
    image: redis:5.0-alpine
    volumes:
      - sentry-redis:/data

  postgres-test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: sent
      POSTGRES_DB: sent
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - sentry-postges:/var/lib/postgresql/data

volumes:
  sentry-data:
  sentry-postges:
  sentry-redis:
